##                                        Topics to be covered
* Vectorization in Practice
* Broadcasting
* Going ahead with few more mathematical operations


In [24]:
#                                              Vectorize implementation

import numpy as np

num = 10000000

In [25]:
a = np.random.random(num)    #array of 10 million numbers
b = np.random.random(num)     # two different arrays.

In [26]:
import time
start = time.time()
c = np.dot(a,b)
end = time.time()
print(c)
print("Verctorize  : " +  str((end -start)*1000) + 'ms')   # multiplyin by 1000 beacuse it gives in form of a nano-second

2500122.658990455
Verctorize  : 14.430999755859375ms


In [27]:
#                                           Non-vectorize implementation
start = time.time()
c =0
for i in range(num):
    c += a[i]*b[i]
end = time.time()
print(c)
print("Loop version  : " +  str((end -start)*1000) + 'ms')

2500122.658990584
Loop version  : 5084.439039230347ms


## Broadcasting : Treats arrays with different shapes during arithmetic operations.
##  the smaller array is “broadcast” across the larger array so that they have compatible shapes.

### General Broadcasting Rules
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

* they are equal, or
* one of them is 1

In [28]:
# NumPy operations are usually done on pairs of arrays on an element-by-element basis.
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [29]:
# NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints.
a = np.array([1.0, 2.0, 3.0])
b = 2.0

a * b

array([2., 4., 6.])

In [30]:
# A bit not too straight example of Broadcasting.
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

a[:, np.newaxis] + b  # we are getting the extra row at the top of the existing row. Just because of Numpy.


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

[link for exploring Broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

In [ ]:
# Number of ufunc available are:
- Arithmetic function: +,-,/,//,%,**
- Bitwise function - &,|,^,<<,>>
- Comparison Operators - <>, <=, >=, ==, !=
- Trignometry Family - np.sin, np.cos, np.tan
- Special Functions - scipy.special.* 

In [41]:
M = np.random.randint(25, size=(3, 4))
M

array([[ 3,  3, 13,  5],
       [20, 23, 15, 14],
       [11, 18, 17,  4]])

In [42]:
M.sum(axis = 0)   # sum of all the columns

array([34, 44, 45, 23])

In [43]:
M.sum(axis = 1)       #sum of all the rows

array([24, 72, 50])

## Many aggregators that are used are:

In [ ]:
np.mean()    np.max()    np.sum()    np.prod()    np.min()    np.std()    np.var()
np.any()     np.all()    np.media()  np.percentile()     np.argmin()      np.argmax()
np.nanmin()   np.nanmax()     np.nansum()